/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tag.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

import com.gradle.scan.plugin.BuildScanExtension;

/**
 * A simple 'hello world' plugin.
 */
public class TagPluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        BuildScanExtension buildScan = (BuildScanExtension) project.getRootProject().getExtensions().getByName("buildScan");
        buildScan.tag("FROM_PLUGIN-" + project.getName());
    }
}
