/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("bs.kotlin.java-library-conventions")
    id("tag.plugin.greeting")
}

val buildScan = rootProject.extensions.getByName("buildScan") as com.gradle.scan.plugin.BuildScanExtension
buildScan.tag("SUBPROJECT_BUILD")
