/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bs.kotlin.app;

import bs.kotlin.list.LinkedList;

import static bs.kotlin.utilities.StringUtils.join;
import static bs.kotlin.utilities.StringUtils.split;
import static bs.kotlin.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
